version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_ITCHYSATS_IP
      APP_PORT: 8000

  web:
    image: ghcr.io/itchysats/itchysats/taker:0.4.21@sha256:289164deb159c735af48cfe1332653e803b69485129ac7727aaf37de3dd6a3f5
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --password=$APP_PASSWORD
      - --umbrel-seed=$APP_SEED
      - $APP_BITCOIN_NETWORK
      - --electrum=tcp://$APP_ELECTRS_NODE_IP:$APP_ELECTRS_NODE_PORT

    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP
