version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_ITCHYSATS_IP
      APP_PORT: 8000

  web:
    image: ghcr.io/itchysats/itchysats/taker:0.6.0@sha256:5d58c5015789b66bbb9a11fb3235651281c9d09aee47ab1c8dcf562dec767835
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --password=$APP_PASSWORD
      - --umbrel-seed=$APP_SEED
      - $APP_BITCOIN_NETWORK
      - --electrum=tcp://$APP_ELECTRS_NODE_IP:$APP_ELECTRS_NODE_PORT
    environment:
      - ITCHYSATS_ENV=umbrel

    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP
