version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_ITCHYSATS_IP
      APP_PORT: 8000

  web:
    image: ghcr.io/itchysats/itchysats/taker:0.7.0@sha256:ba30d0810ec2e08ef2731939f543832e4c26f66c50ccfe54d7265a700894a6bc
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --password=$APP_PASSWORD
      - --app-seed=$APP_SEED
      - $APP_BITCOIN_NETWORK
      - --electrum=tcp://$APP_ELECTRS_NODE_IP:$APP_ELECTRS_NODE_PORT
    environment:
      - ITCHYSATS_ENV=umbrel

    networks:
      default:
        ipv4_address: $APP_ITCHYSATS_IP
